# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 11:27
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('content', catalog.models.MarkdownField()),
                ('content_fr', catalog.models.MarkdownField(null=True)),
                ('content_en', catalog.models.MarkdownField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePagePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('title_fr', models.CharField(max_length=128, null=True)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('content', catalog.models.MarkdownField()),
                ('content_fr', catalog.models.MarkdownField(null=True)),
                ('content_en', catalog.models.MarkdownField(null=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.HomePage')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('slug', models.SlugField()),
                ('content', catalog.models.MarkdownField()),
                ('content_fr', catalog.models.MarkdownField(null=True)),
                ('content_en', catalog.models.MarkdownField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
    ]
