# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 14:25
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import harmonic.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128)),
                ('reference', models.CharField(max_length=32)),
                ('itunes_url', models.URLField()),
                ('is_digital_release', models.BooleanField(default=False)),
                ('description', harmonic.fields.MarkdownField()),
                ('description_fr', harmonic.fields.MarkdownField(null=True)),
                ('description_en', harmonic.fields.MarkdownField(null=True)),
                ('musicological_text', harmonic.fields.MarkdownField()),
                ('musicological_text_fr', harmonic.fields.MarkdownField(null=True)),
                ('musicological_text_en', harmonic.fields.MarkdownField(null=True)),
                ('instrument_name', models.CharField(max_length=255)),
                ('instrument_name_fr', models.CharField(max_length=255, null=True)),
                ('instrument_name_en', models.CharField(max_length=255, null=True)),
                ('instrument_text', harmonic.fields.MarkdownField()),
                ('instrument_text_fr', harmonic.fields.MarkdownField(null=True)),
                ('instrument_text_en', harmonic.fields.MarkdownField(null=True)),
                ('track_list', harmonic.fields.MarkdownField()),
                ('press_review', harmonic.fields.MarkdownField()),
                ('press_review_fr', harmonic.fields.MarkdownField(null=True)),
                ('press_review_en', harmonic.fields.MarkdownField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bio', harmonic.fields.MarkdownField()),
                ('bio_fr', harmonic.fields.MarkdownField(null=True)),
                ('bio_en', harmonic.fields.MarkdownField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.TextField()),
                ('title', models.CharField(max_length=128)),
                ('title_fr', models.CharField(max_length=128, null=True)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('title_color', colorfield.fields.ColorField(default='#000000', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='catalog.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='sections',
            field=models.ManyToManyField(to='catalog.Section'),
        ),
    ]
