# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
