# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='seo_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='seo_description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='seo_keywords_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='seo_keywords_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='seo_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='seo_description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='seo_keywords_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='seo_keywords_fr',
            field=models.TextField(null=True),
        ),
    ]
