# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 12:47
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20151210_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title_color',
            field=colorfield.fields.ColorField(default='#ff0000', max_length=10),
        ),
    ]
