# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import harmonic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20151210_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128)),
                ('reference', models.CharField(max_length=32)),
                ('itunes_url', models.URLField()),
                ('is_digital_release', models.BooleanField(default=False)),
                ('description', harmonic.fields.MarkdownField()),
                ('description_fr', harmonic.fields.MarkdownField(null=True)),
                ('description_en', harmonic.fields.MarkdownField(null=True)),
                ('musicological_text', harmonic.fields.MarkdownField()),
                ('musicological_text_fr', harmonic.fields.MarkdownField(null=True)),
                ('musicological_text_en', harmonic.fields.MarkdownField(null=True)),
                ('instrument_name', models.CharField(max_length=255)),
                ('instrument_text', harmonic.fields.MarkdownField()),
                ('instrument_text_fr', harmonic.fields.MarkdownField(null=True)),
                ('instrument_text_en', harmonic.fields.MarkdownField(null=True)),
                ('track_list', harmonic.fields.MarkdownField()),
                ('press_review', harmonic.fields.MarkdownField()),
                ('press_review_fr', harmonic.fields.MarkdownField(null=True)),
                ('press_review_en', harmonic.fields.MarkdownField(null=True)),
                ('artists', models.ManyToManyField(to='catalog.Artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='section',
            old_name='description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='keywords',
            new_name='seo_keywords',
        ),
        migrations.AddField(
            model_name='album',
            name='sections',
            field=models.ManyToManyField(to='catalog.Section'),
        ),
    ]
