# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import harmonic.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renderer', '0002_auto_20151210_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renderer.MasterImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.TextField()),
                ('content', harmonic.fields.MarkdownField()),
                ('content_fr', harmonic.fields.MarkdownField(null=True)),
                ('content_en', harmonic.fields.MarkdownField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePagePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('title_fr', models.CharField(max_length=128, null=True)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('content', harmonic.fields.MarkdownField()),
                ('content_fr', harmonic.fields.MarkdownField(null=True)),
                ('content_en', harmonic.fields.MarkdownField(null=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.HomePage')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.TextField()),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=128)),
                ('title_fr', models.CharField(max_length=128, null=True)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('content', harmonic.fields.MarkdownField()),
                ('content_fr', harmonic.fields.MarkdownField(null=True)),
                ('content_en', harmonic.fields.MarkdownField(null=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renderer.MasterImage')),
            ],
            options={
                'verbose_name_plural': 'simple pages',
                'verbose_name': 'simple page',
            },
        ),
    ]
