# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'simple page', 'verbose_name_plural': 'simple pages'},
        ),
    ]
