# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20151215_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='seo_keywords_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_keywords_fr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_keywords_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_keywords_fr',
        ),
    ]
