# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20151210_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='keywords',
            new_name='seo_keywords',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='keywords',
            new_name='seo_keywords',
        ),
    ]
